### ISSUE TITLE
Research: Get List of Languages and purposes

### ISSUE THREAD

**Issue by allendewilzin** [Terafirma/Amatuer-Game#1]
We need to get languages and all their purposes

**Comment by allendewilzin** [comment]
@Terafirma Check it

**Comment by Terafirma** [comment]
Checking out: https://unity3d.com/

**Comment by allendewilzin** [comment]
@Terafirma Do you agree that Unity would be the best language to take?

**Comment by Terafirma** [comment]
:+1: Seems like a good fit for now, unity like a good cross platform language to use.
